In [ ]:
import pandas as pd

# URL of the CSV file
url = '/content/Hwy26Crashes2019_S23.csv'

# Read the CSV file from the URL into a DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame to check it
print(df.head(15))

    Crash ID  Record Type  Vehicle ID  Participant ID  \
0    1809119            1         NaN             NaN
1    1809119            2   3409578.0             NaN
2    1809119            3   3409578.0       3887884.0
3    1809119            2   3409579.0             NaN
4    1809119            3   3409579.0       3887885.0
5    1809229            1         NaN             NaN
6    1809229            2   3409765.0             NaN
7    1809229            3   3409765.0       3888073.0
8    1809229            3         0.0       3888074.0
9    1809637            1         NaN             NaN
10   1809637            2   3410470.0             NaN
11   1809637            3   3410470.0       3888766.0
12   1810874            1         NaN             NaN
13   1810874            2   3412622.0             NaN
14   1810874            3   3412622.0       3890872.0

    Participant Display Seq#  Vehicle Coded Seq#  Participant Vehicle Seq#  \
0                        NaN                 NaN                       NaN
1                        NaN                 1.0                       NaN
2                        1.0                 1.0                       1.0
3                        NaN                 2.0                       NaN
4                        2.0                 2.0                       1.0
5                        NaN                 NaN                       NaN
6                        NaN                 1.0                       NaN
7                        1.0                 1.0                       1.0
8                        2.0                 NaN                       1.0
9                        NaN                 NaN                       NaN
10                       NaN                 1.0                       NaN
11                       1.0                 1.0                       1.0
12                       NaN                 NaN                       NaN
13                       NaN                 1.0                       NaN
14                       1.0                 1.0                       1.0

    Serial #  Crash Month  Crash Day  ...  Participant Cause 2 Code  \
0    99992.0          3.0       14.0  ...                       NaN
1        NaN          NaN        NaN  ...                       NaN
2        NaN          NaN        NaN  ...                       NaN
3        NaN          NaN        NaN  ...                       NaN
4        NaN          NaN        NaN  ...                       NaN
5     2405.0          3.0        3.0  ...                       NaN
6        NaN          NaN        NaN  ...                       NaN
7        NaN          NaN        NaN  ...                       NaN
8        NaN          NaN        NaN  ...                       NaN
9     1811.0          5.0       17.0  ...                       NaN
10       NaN          NaN        NaN  ...                       NaN
11       NaN          NaN        NaN  ...                       NaN
12   99981.0          4.0        7.0  ...                       NaN
13       NaN          NaN        NaN  ...                       NaN
14       NaN          NaN        NaN  ...                       NaN

    Participant Cause 3 Code  Participant Event 1 Code  \
0                        NaN                       NaN
1                        NaN                       NaN
2                        0.0                       9.0
3                        NaN                       NaN
4                        NaN                       9.0
5                        NaN                       NaN
6                        NaN                       NaN
7                        NaN                       0.0
8                        0.0                       9.0
9                        NaN                       NaN
10                       NaN                       NaN
11                       0.0                       9.0
12                       NaN                       NaN
13                       NaN                       NaN
14                       4.0                       0.0

    Participant Event 2 Code  Participant Event 3 Code  BAC Test Results Code  \
0                        NaN                       NaN                    NaN
1                        NaN                       NaN                    NaN
2                        0.0                       0.0                    NaN
3                        NaN                       NaN                    NaN
4                        9.0                       0.0                    NaN
5                        NaN                       NaN                    NaN
6                        NaN                       NaN                    NaN
7                        0.0                       0.0                    NaN
8                        1.0                       0.0                    NaN
9                        NaN                       NaN                    NaN
10                       NaN                       NaN                    NaN
11                       0.0                       0.0                    NaN
12                       NaN                       NaN                    NaN
13                       NaN                       NaN                    NaN
14                       0.0                       0.0                    NaN

    Alcohol Use Reported  Drug Use Reported  \
0                    NaN                NaN
1                    NaN                NaN
2                    NaN                NaN
3                    NaN                NaN
4                    NaN                NaN
5                    NaN                NaN
6                    NaN                NaN
7                    NaN                NaN
8                    NaN                NaN
9                    NaN                NaN
10                   NaN                NaN
11                   NaN                NaN
12                   NaN                NaN
13                   NaN                NaN
14                   NaN                NaN

    Participant Marijuana Use Reported  Participant Striker Flag
0                                  NaN                       NaN
1                                  NaN                       NaN
2                                  NaN                       NaN
3                                  NaN                       NaN
4                                  NaN                       NaN
5                                  NaN                       NaN
6                                  NaN                       NaN
7                                  NaN                       NaN
8                                  NaN                       NaN
9                                  NaN                       NaN
10                                 NaN                       NaN
11                                 NaN                       NaN
12                                 NaN                       NaN
13                                 NaN                       NaN
14                                 NaN                       NaN

[15 rows x 157 columns]

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
url = '/content/Hwy26Crashes2019_S23.csv'
df = pd.read_csv(url)

# EXISTENCE ASSERTIONS
# Check that every crash occurred on a date
assert df['Crash Day'].notnull().all()
assert df['Crash Month'].notnull().all()

# Check that every crash has an ID
assert df['Crash ID'].notnull().all()

# Check that every crash has a Vehicle ID
assert df['Vehicle ID'].notnull().all()

# LIMIT ASSERTIONS
# Check that every weekday is between 1 and 7
assert df['Week Day Code'].between(1, 7).all()

# Check that every crash month is between 1 and 12
assert df['Crash Month'].between(1, 12).all()

# INTRA-RECORD ASSERTIONS
# If a crash record has a crash day, it should have a crash month
assert np.all(df[df['Crash Day'].notnull()]['Crash Month'].notnull())
# If a crash record has a crash Month, it should have a crash year
assert np.all(df[df['Crash Month'].notnull()]['Crash Year'].notnull())

# INTER-RECORD CHECKS
# Check that every Vehicle ID has a known Participant ID
assert df.set_index('Vehicle ID')['Participant ID'].notnull().all()

# SUMMARY ASSERTIONS
# Assert there are thousands but not millions of participants
participant_count = df['Participant ID'].nunique()
assert 1000 <= participant_count < 1000000

# Check uniqueness of (Crash ID, Record Type, Vehicle ID)
assert df[['Crash ID', 'Record Type', 'Vehicle ID']].drop_duplicates().shape[0] == df.shape[0]

# STATISTICAL DISTRIBUTION ASSERTIONS
# Check if Participant ID and Vehicle ID counts are roughly the same
participant_count = df['Participant ID'].count()
vehicle_count = df['Vehicle ID'].count()
assert abs(participant_count - vehicle_count) < max(participant_count, vehicle_count) * 0.1

# Check if crashes are evenly distributed throughout the days of the week
days_distribution = df['Crash Day'].value_counts(normalize=True)
assert np.allclose(days_distribution, 1/7, atol=0.03)

print("All assertions passed.")

AssertionError:

In [ ]:
df_type1 = df[df['Record Type'] == 1]
df_type2 = df[df['Record Type'] == 2]
df_type3 = df[df['Record Type'] == 3]

# EXISTENCE ASSERTIONS

# Check that every crash has an ID
assert df['Crash ID'].notnull().all()
assert df_type2['Vehicle ID'].notnull().all()

# Check that every crash of type 1 occurred on a date
assert df_type1['Crash Day'].notnull().all()
assert df_type1['Crash Month'].notnull().all()

# LIMIT ASSERTIONS
# Check that every weekday is between 1 and 7
assert df_type1['Week Day Code'].between(1, 7).all()
assert df_type1['Crash Month'].between(1, 12).all()

# INTRA-RECORD ASSERTIONS
# If a crash record has a crash day, it should have a crash month
assert df[df['Crash Day'].notnull()]['Crash Month'].notnull().all()
# If a crash record has a crash Month, it should have a crash year
assert df[df['Crash Month'].notnull()]['Crash Year'].notnull().all()

# INTER-RECORD CHECKS
# Check that every Vehicle ID has a known Participant ID
assert df_type3.set_index('Vehicle ID')['Participant ID'].notnull().all()

# Check that each Vehicle ID in records where both are present has at least one corresponding Participant ID
vehicle_participant_check = df.dropna(subset=['Vehicle ID', 'Participant ID'])
grouped = vehicle_participant_check.groupby('Vehicle ID')['Participant ID'].nunique()
assert (grouped > 0).all()

# SUMMARY ASSERTIONS
# Assert there are thousands but not millions of participants
participant_count = df['Participant ID'].nunique()
assert 1000 <= participant_count < 1000000

# Check uniqueness of (Crash ID, Record Type, Vehicle ID)
assert df[['Crash ID', 'Record Type', 'Vehicle ID', "Participant ID"]].drop_duplicates().shape[0] == df.shape[0]

# STATISTICAL DISTRIBUTION ASSERTIONS
# Check if crashes are evenly distributed throughout the days of the week
days_distribution = df['Week Day Code'].value_counts(normalize=True)
assert np.allclose(days_distribution, 1/7, atol=0.03)

# Check if crashes are evenly distributed throughout the days of the week
days_distribution = df['Crash Day'].value_counts(normalize=True)
assert np.allclose(days_distribution, 1/31, atol=0.03)


print("All assertions passed.")

All assertions passed.

In [ ]:
import pandas as pd
url = '/content/Hwy26Crashes2019_S23.csv'
df = pd.read_csv(url)
record_types = df['Record Type'].unique()

for record_type in record_types:
    df_subset = df[df['Record Type'] == record_type]
    filename = f'record_type_{record_type}_data.csv'
    df_subset.to_csv(filename, index=False)
    print(f'Saved {filename} with {len(df_subset)} records')

Saved record_type_1_data.csv with 508 records
Saved record_type_2_data.csv with 1015 records
Saved record_type_3_data.csv with 1216 records

In [ ]:
url = '/content/record_type_1_data.csv'
df_type1 = pd.read_csv(url)
df_type1.head()

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
0,1809119,1,NaN,NaN,NaN,NaN,NaN,99992.0,3.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1809229,1,NaN,NaN,NaN,NaN,NaN,2405.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1809637,1,NaN,NaN,NaN,NaN,NaN,1811.0,5.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1810874,1,NaN,NaN,NaN,NaN,NaN,99981.0,4.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1812266,1,NaN,NaN,NaN,NaN,NaN,5970.0,7.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
url = '/content/record_type_2_data.csv'
df_type2 = pd.read_csv(url)
df_type2.head()

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
0,1809119,2,3409578.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1809119,2,3409579.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1809229,2,3409765.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1809637,2,3410470.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1810874,2,3412622.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
url = '/content/record_type_3_data.csv'
df_type3 = pd.read_csv(url)
df_type3.head()

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
0,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,9.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN
2,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,1809229,3,0.0,3888074.0,2.0,NaN,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
4,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

0       True
5       True
9       True
12      True
16      True
        ...
2716    True
2719    True
2724    True
2729    True
2734    True
Name: Crash Month, Length: 508, dtype: bool